/**
 * Render a declarative policy → Claw Patrol HCL (CEL rules), matching the spike's
 * `~/clawpatrol/bough.hcl` structure. bough owns the HCL: it never hand-edits it,
 * it composes bundles (see bundles.ts) into this shape and renders.
 *
 * The runtime mirror of these rules lives in policy.ts (used for preview/tests);
 * the gateway enforces the rendered HCL at L3. Keep the two in step — a bundle's
 * fixtures (run via `clawpatrol test`) are the regression harness that they are.
 *
 * Precedence gotcha carried over from the spike: Claw Patrol is FIRST-MATCH, not
 * deny-wins. Order rules narrow→broad (e.g. graphql-mutation before graphql-query
 * before the REST method rules). Rule order in `rules[]` is the emitted order.
 */

import type { Verdict } from "./policy.ts";

export interface HclWireguard {
  subnetCidr: string;
  endpoint: string;
  // The actual UDP bind. Defaults to 51820 upstream, which collides with an
  // installed Clawpatrol.app system extension — bough pins a free port here.
  listenPort?: number;
  // The 127.0.0.1 TCP landing pad host-local clients dial (default 8443 upstream).
  hostLoopbackPort?: number;
}

export interface HclGateway {
  dashboardListen: string;
  stateDir: string;
  publicUrl: string;
  wireguard: HclWireguard;
}

/** `credential "<type>" "<name>" { endpoint = <endpointRef> }` */
export interface HclCredential {
  type: string; // e.g. "bearer_token"
  name: string; // e.g. "github_pat"
  endpoint: string; // endpoint ref, e.g. "https.github"
}

/**
 * `endpoint "<kind>" "<name>" { ... }`. https carries `hosts`; postgres a single
 * `host`; kubernetes takes no host body (the gateway learns API-server hosts).
 */
export interface HclEndpoint {
  kind: "https" | "kubernetes" | "postgres" | (string & {});
  name: string;
  hosts?: string[];
  host?: string;
}

/** `rule "<name>" { endpoint = <ref>; condition = <CEL>; verdict; reason? }` */
export interface HclRule {
  name: string;
  endpoint: string; // endpoint ref, e.g. "https.github"
  condition: string; // CEL expression
  verdict: Verdict;
  reason?: string;
  /** hold-and-ask: named approvers, emitted as `approve = [human_approver.x]`. */
  approve?: string[];
}

export interface HclProfile {
  name: string;
  credentials: string[]; // credential refs, e.g. "bearer_token.github_pat"
}

export interface HclPolicy {
  gateway: HclGateway;
  credentials: HclCredential[];
  endpoints: HclEndpoint[];
  rules: HclRule[];
  profiles: HclProfile[];
}

const q = (s: string) => JSON.stringify(s); // HCL strings are JSON-compatible
const list = (xs: string[]) => "[" + xs.map(q).join(", ") + "]";

function renderGateway(g: HclGateway): string {
  return [
    "gateway {",
    `  dashboard_listen = ${q(g.dashboardListen)}`,
    `  state_dir  = ${q(g.stateDir)}`,
    `  public_url = ${q(g.publicUrl)}`,
    "  wireguard {",
    `    subnet_cidr = ${q(g.wireguard.subnetCidr)}`,
    // single-host loopback needs an explicit endpoint (spike gotcha).
    `    endpoint    = ${q(g.wireguard.endpoint)}`,
    ...(g.wireguard.listenPort ? [`    listen_port = ${g.wireguard.listenPort}`] : []),
    ...(g.wireguard.hostLoopbackPort ? [`    host_loopback_port = ${g.wireguard.hostLoopbackPort}`] : []),
    "  }",
    "}",
  ].join("\n");
}

function renderCredential(c: HclCredential): string {
  return `credential ${q(c.type)} ${q(c.name)} { endpoint = ${c.endpoint} }`;
}

function renderEndpoint(e: HclEndpoint): string {
  const body: string[] = [];
  if (e.hosts) body.push(`hosts = ${list(e.hosts)}`);
  if (e.host) body.push(`host = ${q(e.host)}`);
  const inner = body.length ? ` ${body.join("; ")} ` : "";
  return `endpoint ${q(e.kind)} ${q(e.name)} {${inner}}`;
}

function renderRule(r: HclRule): string {
  const lines = [
    `rule ${q(r.name)} {`,
    `  endpoint  = ${r.endpoint}`,
    `  condition = ${q(r.condition)}`,
    `  verdict   = ${q(r.verdict)}`,
  ];
  if (r.approve?.length) lines.push(`  approve   = [${r.approve.join(", ")}]`);
  if (r.reason) lines.push(`  reason    = ${q(r.reason)}`);
  lines.push("}");
  return lines.join("\n");
}

function renderProfile(p: HclProfile): string {
  return [
    `profile ${q(p.name)} {`,
    `  credentials = [${p.credentials.join(", ")}]`,
    "}",
  ].join("\n");
}

/** Render a full policy to HCL text the Claw Patrol gateway can load. */
export function renderHcl(p: HclPolicy): string {
  const blocks: string[] = [
    "# Generated by bough — do not hand-edit. Composed from policy bundles.",
    renderGateway(p.gateway),
    ...p.credentials.map(renderCredential),
    ...p.endpoints.map(renderEndpoint),
    ...p.rules.map(renderRule),
    ...p.profiles.map(renderProfile),
  ];
  return blocks.join("\n\n") + "\n";
}

/**
 * Gateway defaults for bough's single-host loopback deployment. Ports are chosen
 * to avoid two known collisions on the dev box: :8080 (bough's llama-server) and
 * :51820 (an installed Clawpatrol.app system extension's WireGuard).
 */
export function defaultGateway(overrides: Partial<HclGateway> = {}): HclGateway {
  return {
    dashboardListen: "127.0.0.1:8090",
    stateDir: "state",
    publicUrl: "http://127.0.0.1:8090",
    wireguard: {
      subnetCidr: "10.55.0.0/24",
      endpoint: "127.0.0.1:51999",
      listenPort: 51999,
      hostLoopbackPort: 8453,
    },
    ...overrides,
  };
}
