//! Invariant: the committed table is a STABLE function of the catalog — sorted by name — so a diff
//! of `docs/event-catalog.md` shows what changed about the events and nothing about scan order.

use std::collections::BTreeMap;

use crate::scan::{Catalog, SiteKind};

/// §15 item 7's threshold: the gate is worth having past ~30 events.
pub const CATALOG_FLOOR: usize = 30;

/// How many DISTINCT event names the catalog holds.
pub fn event_count(c: &Catalog) -> usize {
    c.decls
        .iter()
        .map(|d| (&d.name, &d.ty))
        .collect::<std::collections::BTreeSet<_>>()
        .len()
}

/// The committed table: name | mode | type | crate | dispatch sites | listen sites.
pub fn table(c: &Catalog) -> String {
    let mut dispatches: BTreeMap<&str, usize> = BTreeMap::new();
    let mut listens: BTreeMap<&str, usize> = BTreeMap::new();
    for s in &c.sites {
        let m = match s.kind {
            SiteKind::Dispatch => &mut dispatches,
            SiteKind::Listen => &mut listens,
        };
        *m.entry(s.ty.as_str()).or_default() += 1;
    }

    // Sorted by (name, type, crate): a stable total order that does not depend on scan order.
    let mut rows: Vec<_> = c.decls.iter().collect();
    rows.sort_by(|a, b| {
        (&a.name, &a.ty, &a.krate, &a.line).cmp(&(&b.name, &b.ty, &b.krate, &b.line))
    });
    rows.dedup_by(|a, b| a.name == b.name && a.ty == b.ty && a.trait_mode == b.trait_mode);

    let mut out = String::new();
    out.push_str("# Event catalog\n\n");
    out.push_str(
        "GENERATED by `cargo xtask events --write`. REQUIREMENTS §15 item 7: every kernel event\nwith its declared dispatch mode, checked against every dispatch site. Do not edit by hand.\n\n",
    );
    out.push_str(&format!("{} events.\n\n", event_count(c)));
    out.push_str("| name | mode | type | crate | dispatch sites | listen sites |\n");
    out.push_str("| --- | --- | --- | --- | --- | --- |\n");
    for d in rows {
        out.push_str(&format!(
            "| `{}` | {} | `{}` | {} | {} | {} |\n",
            d.name,
            d.effective_mode().as_str(),
            d.ty,
            d.krate,
            dispatches.get(d.ty.as_str()).copied().unwrap_or(0),
            listens.get(d.ty.as_str()).copied().unwrap_or(0),
        ));
    }
    out
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::scan::{DispatchMode, DispatchSite, EventDecl};
    use std::path::PathBuf;

    fn decl(name: &str, ty: &str, mode: DispatchMode) -> EventDecl {
        EventDecl {
            name: name.into(),
            ty: ty.into(),
            trait_mode: mode,
            declared_mode: None,
            krate: "fixture".into(),
            file: PathBuf::from("crates/fixture/src/lib.rs"),
            line: 1,
        }
    }

    #[test]
    fn every_declared_event_gets_a_row() {
        let c = Catalog {
            decls: vec![
                decl("b/two", "Two", DispatchMode::Serial),
                decl("a/one", "One", DispatchMode::Emit),
            ],
            sites: vec![DispatchSite {
                ty: "One".into(),
                mode: DispatchMode::Emit,
                kind: SiteKind::Dispatch,
                file: PathBuf::from("crates/fixture/src/lib.rs"),
                line: 5,
            }],
        };
        let t = table(&c);
        assert!(
            t.contains("| `a/one` | emit | `One` | fixture | 1 | 0 |"),
            "{t}"
        );
        assert!(
            t.contains("| `b/two` | serial | `Two` | fixture | 0 | 0 |"),
            "{t}"
        );
        assert!(t.contains("2 events."), "{t}");
    }

    #[test]
    fn the_table_is_sorted_by_name_and_is_stable() {
        let a = decl("a/one", "One", DispatchMode::Emit);
        let b = decl("b/two", "Two", DispatchMode::Serial);
        let forward = Catalog {
            decls: vec![a.clone(), b.clone()],
            sites: vec![],
        };
        let reversed = Catalog {
            decls: vec![b, a],
            sites: vec![],
        };
        let t = table(&forward);
        assert_eq!(t, table(&reversed), "scan order must not change the table");
        let one = t.find("a/one").unwrap();
        let two = t.find("b/two").unwrap();
        assert!(one < two, "sorted by name:\n{t}");
    }
}
