import { assert, assertEquals, assertThrows } from "jsr:@std/assert@1";
import { githubBundle } from "./bundles.ts";
import { installBundle, InstallError, isInstalled, validateInstall } from "./install.ts";

Deno.test("validateInstall: github default renders HCL and passes its fixtures", () => {
  const r = validateInstall(githubBundle);
  assertEquals(r.ok, true);
  assertEquals(r.fixtures.length, 4);
  assert(r.fixtures.every((f) => f.ok));
  assert(r.hcl.includes("api.github.com"));
  assert(r.hcl.includes('rule "github-graphql-mutation"'));
});

Deno.test("validateInstall: allowWrites relaxes writes, so default-deny fixtures fail", () => {
  const r = validateInstall(githubBundle, { allowWrites: true });
  // Fixtures encode the default (deny writes) regression, so relaxing writes fails them.
  assertEquals(r.ok, false);
  assert(r.fixtures.some((f) => !f.ok));
});

Deno.test("validateInstall: wrong param type throws InstallError", () => {
  assertThrows(
    () => validateInstall(githubBundle, { host: 123 as unknown as string }),
    InstallError,
    "must be a string",
  );
});

Deno.test("installBundle: writes the rendered HCL and marks installed", async () => {
  const dir = await Deno.makeTempDir();
  const r = await installBundle(githubBundle, {}, dir);
  assertEquals(r.ok, true);
  assertEquals(isInstalled("github", dir), true);
  assertEquals(isInstalled("nope", dir), false);
  const written = await Deno.readTextFile(`${dir}/github.hcl`);
  assert(written.includes("Generated by bough"));
  await Deno.remove(dir, { recursive: true });
});
