[package]
name = "bough-plugin-request-recorder"
version = "0.1.0"
edition = "2021"
autotests = false

[lib]
path = "src/lib.rs"

[dependencies]
bough-kernel = { workspace = true }
bough-plugin-llm = { workspace = true }
bough-llm = { workspace = true }
bough-util = { workspace = true }
async-trait = { workspace = true }
chrono = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
schemars = { workspace = true }
sha2 = { workspace = true }
tracing = { workspace = true }
