/**
 * Advisory annotations — one-line, plain-English context generated by the LOCAL
 * worker, fire-and-forget. Nothing gates on these: a missing or wrong annotation
 * costs a hover, not a verdict. Both helpers return null on any failure (worker
 * cold, timeout, junk reply) and never throw; callers publish only non-null
 * results. Schema-constrained decoding keeps the replies structurally parseable.
 */
import type { NetRequest } from "../schema/parts.ts";
import { workerIfRunning } from "./runtime.ts";
import { workerComplete } from "./client.ts";
import { frontierComplete, frontierWorkerModel } from "./frontier.ts";

const DEADLINE_MS = 5_000;

const SUMMARY_SCHEMA = {
  type: "object",
  properties: { summary: { type: "string" } },
  required: ["summary"],
  additionalProperties: false,
};

const NET_SYSTEM = [
  "A sandboxed coding agent made an HTTP request that is HELD for human approval.",
  "In one short plain-English sentence, tell the human what the request does and to",
  'what — e.g. "Creates a fork of the anthropics/claude-code repo". Reply as JSON',
  '{"summary": "..."}. No hedging, no "this request appears to".',
].join(" ");

/** One-liner for a held egress request, shown on the approval card. */
export function annotateNet(record: NetRequest): Promise<string | null> {
  const user = [
    `${record.verb ?? "?"} to host ${record.host}`,
    `classified action: ${record.action}`,
    record.fields ? `parsed fields: ${JSON.stringify(record.fields)}` : "",
    record.requestedBy ? `requested by: ${record.requestedBy}` : "",
  ].filter(Boolean).join("\n");
  return oneLiner(NET_SYSTEM, user, 140);
}

const ACTIVITY_SYSTEM = [
  "In 3 to 8 words, present tense, say what this coding-agent step is doing —",
  'like "running the test suite" or "refactoring the proxy gate". Reply as JSON',
  '{"summary": "..."}. No trailing period, no quotes inside.',
].join(" ");

/** Blurb for the live map: what a session's current program round is doing. */
export function activityBlurb(programCode: string, outputHead: string): Promise<string | null> {
  const user = `PROGRAM:\n${programCode.slice(0, 1200)}\n\nOUTPUT (start):\n${
    outputHead.slice(0, 400)
  }`;
  return oneLiner(ACTIVITY_SYSTEM, user, 60);
}

async function oneLiner(system: string, user: string, cap: number): Promise<string | null> {
  let timer: ReturnType<typeof setTimeout> | undefined;
  const deadline = new Promise<null>((r) => {
    timer = setTimeout(() => r(null), DEADLINE_MS);
  });
  try {
    const raw = await Promise.race([
      (async () => {
        if (frontierWorkerModel()) {
          return await frontierComplete({ system, user, maxTokens: 96, jsonSchema: SUMMARY_SCHEMA });
        }
        const url = await workerIfRunning();
        if (!url) return null;
        return await workerComplete(url, {
          system,
          user,
          maxTokens: 96,
          temperature: 0.2,
          jsonSchema: SUMMARY_SCHEMA,
          cachePrompt: true,
        });
      })(),
      deadline,
    ]);
    if (!raw) return null;
    const summary = (JSON.parse(raw) as { summary?: unknown }).summary;
    if (typeof summary !== "string") return null;
    const line = summary.trim().split("\n")[0].replace(/^["'`]+|["'`.]+$/g, "").slice(0, cap)
      .trim();
    return line || null;
  } catch {
    return null;
  } finally {
    clearTimeout(timer);
  }
}
