[package]
name = "bough-tui"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"
repository = "https://github.com/andreylukin/bough"

[dependencies]
bough-core = { workspace = true }
ratatui = { workspace = true }
crossterm = { workspace = true }
termimad = { workspace = true }
tokio = { workspace = true }
tokio-util = { workspace = true }
thiserror = { workspace = true }
reqwest = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
unicode-width = { workspace = true }
regex = { workspace = true }
base64 = { workspace = true }
futures = { workspace = true }
