#!/usr/bin/env bash
# Rebuild the vendored charting bundle under crates/bough-server/src/js/lib.
#
# DELIBERATELY OUT OF BAND. This is not wired into `make gates`, `make build`,
# or CI, and there is no build.rs: a `cargo build` on a clean checkout must not
# need node, npm, or the network. The bundle is COMMITTED, and this script is
# how you bump it — run it, read the diff, commit it.
#
#   make chart-bundle
#
# Versions are pinned here and nowhere else. Bumping one is an edit to this
# file plus the resulting bundle diff, so `git log` on this script is the
# upgrade history.
set -euo pipefail

FLINT_VERSION="0.5.0"      # microsoft/flint-chart — the semantic chart compiler
ECHARTS_VERSION="6.1.0"    # the renderer flint's echarts backend targets
ECHARTS_GL_VERSION="2.1.0" # 3D marks (bar3D/scatter3D/surface/globe) over echarts

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
DEST="$ROOT/crates/bough-server/src/js/lib"
WORK="$(mktemp -d)"
trap 'rm -rf "$WORK"' EXIT

command -v npm >/dev/null || { echo "build-chart-bundle: npm not on PATH" >&2; exit 2; }

echo "build-chart-bundle: installing into $WORK"
cd "$WORK"
npm init -y >/dev/null
npm install --silent --no-audit --no-fund \
  "flint-chart@$FLINT_VERSION" \
  "echarts@$ECHARTS_VERSION" \
  "echarts-gl@$ECHARTS_GL_VERSION"

mkdir -p "$DEST"

# flint has zero runtime dependencies and treats every renderer as an OPTIONAL
# peer, so bundling the echarts backend alone pulls in the compiler and nothing
# else. ESM because the artifact imports it from a module script.
# `--legal-comments=eof` keeps @license/@preserve blocks that minification
# would otherwise drop. These are third-party bundles vendored into an
# Apache-2.0 repo; the notices are an obligation, not decoration.
echo "build-chart-bundle: bundling flint"
npx --yes esbuild node_modules/flint-chart/dist/echarts/index.js \
  --bundle --format=esm --minify --legal-comments=eof --log-level=error \
  --outfile="$DEST/flint.js"

# echarts and echarts-gl ship their own minified UMD builds; rebundling them
# buys nothing and only risks diverging from what upstream tests.
echo "build-chart-bundle: copying echarts"
cp node_modules/echarts/dist/echarts.min.js       "$DEST/echarts.js"
cp node_modules/echarts-gl/dist/echarts-gl.min.js "$DEST/echarts-gl.js"

# Read by the server so /artifacts/_lib/VERSIONS answers "what am I serving?"
# without anyone having to read this script.
cat > "$DEST/VERSIONS" <<EOF
flint-chart $FLINT_VERSION
echarts $ECHARTS_VERSION
echarts-gl $ECHARTS_GL_VERSION
EOF

# The licence texts of everything that ended up in the bundle, copied from the
# packages themselves rather than transcribed. Minification strips most notices
# out of the JS, and shipping the bytes without the terms is not optional —
# echarts-gl in particular pulls in claygl and zrender, which is why this walks
# the installed tree instead of listing the three direct names.
echo "build-chart-bundle: collecting licences"
{
  echo "Third-party licences for the files in this directory."
  echo "Generated by scripts/build-chart-bundle.sh — do not edit by hand."
  rule="======================================================================"
  for pkg in flint-chart echarts echarts-gl claygl zrender; do
    dir="node_modules/$pkg"
    [ -d "$dir" ] || continue
    version="$(node -p "require('./$dir/package.json').version" 2>/dev/null || echo unknown)"
    printf '\n\n%s\n== %s %s\n%s\n\n' "$rule" "$pkg" "$version" "$rule"
    # A plain glob, not `ls | head` — under `set -o pipefail` a no-match `ls`
    # fails the pipeline and takes the whole script with it.
    lic=""
    for cand in "$dir"/LICENSE* "$dir"/LICENCE*; do
      [ -f "$cand" ] && { lic="$cand"; break; }
    done
    if [ -n "$lic" ]; then
      cat "$lic"
    else
      node -p "require('./$dir/package.json').license || 'see package homepage'" 2>/dev/null \
        || echo "see package homepage"
    fi
  done
} > "$DEST/LICENSES"

echo "build-chart-bundle: done"
( cd "$DEST" && for f in *; do printf '  %-14s %8s bytes\n' "$f" "$(wc -c < "$f" | tr -d ' ')"; done )
